#!/usr/bin/python


if __name__ == "__main__":
    if "-write" in argv:
        write_config()
        sys.exit()
    if "-help" in argv:
        print_help()
        sys.exit()

    cfg = get_config()

    # Cleaning step - Don't care if this errors
    log("Cleaning up...")
    shell(f"rm {cfg['bin_path']}*.o")

    # Compilation step
    EXIT_CODE = 0
    log("Compiling...")
    src_files = glob(cfg["source_path"] + "*.c*", recursive=True)
    for f in src_files:
        EXIT_CODE = shell(f"{cfg['compiler']} -c {f} {cfg['compiler_flags']}")
        fail_if(EXIT_CODE != 0, "Compilation failed!")

    # Moving object files to bin directory
    EXIT_CODE = shell(f"mv *.o {cfg['bin_path']}")
    fail_if(EXIT_CODE != 0, "Failed to move object files!")

    # Linking step
    log("Linking...")
    O_FILES = " ".join(glob(f"{cfg['bin_path']}*.o"))
    EXIT_CODE = shell(
        f"{cfg['compiler']} -o {cfg['bin_path']}{cfg['exe_name']} {O_FILES} {cfg['linker_flags']}"
    )
    fail_if(EXIT_CODE != 0, "Linking failed!")
    log("Success!")
